{
 "title": "Service Overview",
 "description": "Operational metrics per service",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,24h,1d,7d,14d,30d"
   },
   { "name": "app", "query": "label_values(app)" }
  ]
 },
 "panels": [
  {
   "title": "Status codes (last 24 hours)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (increase(http_requests_total{app=\"[[app]]\"}[24h]))"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{app=\"[[app]]\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "min(time() - process_start_time_seconds{app=\"[[app]]\"}) ",
     "legendFormat": "Shortest"
    },
    {
     "expr": "max(time() - process_start_time_seconds{app=\"[[app]]\"}) ",
     "legendFormat": "Longest"
    }
   ]
  },
  {
   "title": "Average request duration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (path) (rate(http_request_duration_seconds_sum{app=\"[[app]]\"}[$interval]) /\nrate(http_request_duration_seconds_count{app=\"[[app]]\"}[$interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{app=\"[[app]]\",handler!=\"/api/health\"}[$interval])) without (instance)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "HTTP status codes",
   "type": "graph",
   "description": "http requests increase (rate of 1 minutes)",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (status,path) (round(increase(http_requests_total{app=\"[[app]]\",path!=\"/api/health\"}[$interval])))",
     "legendFormat": "{{ status }} - {{ path }}"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total{app=\"[[app]]\"}[$interval])",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "avg(increase(process_cpu_seconds_total{app=\"[[app]]\"}[$interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{app=\"[[app]]\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "GO Routines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{app=\"[[app]]\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "GO Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{app=\"[[app]]\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Postgres connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "postgresql_open_connections{app=\"[[app]]\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}