{
 "title": "Lendo SE - Detailed Overview",
 "description": "Monitors overall status of the platform",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "fixedinterval", "label": "interval", "query": "1d,2h,1h,30m,15m,5m,1m" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(httpmetrics_requests_total[$fixedinterval]))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(httpmetrics_requests_total{code!~\"2..|3..\"}[$fixedinterval])) - sum(increase(httpmetrics_requests_total{app=~\"response.*\", code=\"404\", path=\"/api/applications/{id}/acceptance\"}[$fixedinterval]))) * 100 / sum(increase(httpmetrics_requests_total[$fixedinterval]))"
    }
   ]
  },
  {
   "title": "Error Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(httpmetrics_requests_total{code=\"404\"}[$fixedinterval])) by (code) - sum(increase(httpmetrics_requests_total{app=~\"response.*\", code=\"404\", path=\"/api/applications/{id}/acceptance\"}[$fixedinterval])) by (code)",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "sum(increase(httpmetrics_requests_total{code!~\"2..|3..|404\"}[$fixedinterval])) by (code) > 0",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Amount of errors per microservice",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(httpmetrics_requests_total{code=\"404\"}[$fixedinterval])) by (app) - sum(increase(httpmetrics_requests_total{app=~\"response.*\", code=\"404\", path=\"/api/applications/{id}/acceptance\"}[$fixedinterval])) by (app)) > 0",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "sum(increase(httpmetrics_requests_total{code!~\"2..|3..|404\"}[$fixedinterval])) by (app) > 0",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Top 1% slowest requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(httpmetrics_request_duration_seconds_bucket[10m])) by (app, le))",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}